#
# Docker installation
#

- name: Apt Https support
  apt: 
    name: "{{ packages }}"
    state: present
    install_recommends: no
  vars:
    packages:
        - gpg
        - apt-transport-https

- apt_key:
    url: https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg
    state: present

- apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable
    state: present
    filename: 'docker'

- name: Install docker-ce
  apt: name=docker-ce state=latest install_recommends=no

- name: Install docker-ce-cli
  apt: name=docker-ce-cli state=latest install_recommends=no

- name: Install docker-compose-plugin
  apt: name=docker-compose-plugin state=latest install_recommends=no

- name: Ensure docker daemon is running
  systemd: name=docker state=started enabled=yes
  ignore_errors: yes


